import { MigrationInterface, QueryRunner } from "typeorm";
export class CommunityLearningPrograms1783500000000 implements MigrationInterface {
  name="CommunityLearningPrograms1783500000000";
  async up(q:QueryRunner):Promise<void>{
    await q.query("ALTER TABLE `community_activities` ADD `endTime` datetime NULL, ADD `joinMode` varchar(24) NOT NULL DEFAULT 'open', ADD `memberLimit` int NULL, ADD `inviteCode` varchar(64) NULL");
    await q.query("CREATE TABLE `community_activity_members` (`id` int NOT NULL AUTO_INCREMENT, `activityId` int NOT NULL, `userId` int NOT NULL, `tenantId` int NULL, `status` varchar(24) NOT NULL DEFAULT 'joined', `applyRemark` varchar(500) NULL, `reviewRemark` varchar(500) NULL, `reviewedByAdminId` int NULL, `reviewedAt` datetime NULL, `joinedAt` datetime NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_community_activity_member_user` (`activityId`,`userId`), PRIMARY KEY (`id`), CONSTRAINT `FK_community_member_activity` FOREIGN KEY (`activityId`) REFERENCES `community_activities`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_community_member_tenant` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE SET NULL) ENGINE=InnoDB");
    await q.query("ALTER TABLE `checkin_tasks` ADD `activityId` int NULL, ADD `checkinType` varchar(24) NOT NULL DEFAULT 'text', ADD `questions` json NULL, ADD `requireApproval` tinyint NOT NULL DEFAULT 0, ADD `allowMakeup` tinyint NOT NULL DEFAULT 0, ADD `makeupWithinDays` int NOT NULL DEFAULT 3");
    await q.query("ALTER TABLE `community_checkins` DROP INDEX `IDX_community_checkins_user_tenant_date`, ADD `activityId` int NULL, ADD `content` text NULL, ADD `images` json NULL, ADD `answers` json NULL, ADD `locationName` varchar(200) NULL, ADD `latitude` decimal(10,6) NULL, ADD `longitude` decimal(10,6) NULL, ADD `status` varchar(24) NOT NULL DEFAULT 'approved', ADD `makeup` tinyint NOT NULL DEFAULT 0, ADD `reviewRemark` varchar(500) NULL, ADD `reviewedByAdminId` int NULL, ADD `reviewedAt` datetime NULL, ADD UNIQUE INDEX `IDX_community_checkins_user_task_date` (`userId`,`taskId`,`date`)");
  }
  async down(q:QueryRunner):Promise<void>{await q.query("ALTER TABLE `community_checkins` DROP INDEX `IDX_community_checkins_user_task_date`, DROP COLUMN `reviewedAt`, DROP COLUMN `reviewedByAdminId`, DROP COLUMN `reviewRemark`, DROP COLUMN `makeup`, DROP COLUMN `status`, DROP COLUMN `longitude`, DROP COLUMN `latitude`, DROP COLUMN `locationName`, DROP COLUMN `answers`, DROP COLUMN `images`, DROP COLUMN `content`, DROP COLUMN `activityId`, ADD UNIQUE INDEX `IDX_community_checkins_user_tenant_date` (`userId`,`tenantId`,`date`)");await q.query("ALTER TABLE `checkin_tasks` DROP COLUMN `makeupWithinDays`, DROP COLUMN `allowMakeup`, DROP COLUMN `requireApproval`, DROP COLUMN `questions`, DROP COLUMN `checkinType`, DROP COLUMN `activityId`");await q.query("DROP TABLE `community_activity_members`");await q.query("ALTER TABLE `community_activities` DROP COLUMN `inviteCode`, DROP COLUMN `memberLimit`, DROP COLUMN `joinMode`, DROP COLUMN `endTime`");}
}
