import { MigrationInterface, QueryRunner } from "typeorm";
export class CourseAssessments1783470000000 implements MigrationInterface {
  name = "CourseAssessments1783470000000";
  async up(q: QueryRunner): Promise<void> {
    await q.query("CREATE TABLE `course_assessments` (`id` int NOT NULL AUTO_INCREMENT, `courseId` int NOT NULL, `tenantId` int NULL, `title` varchar(160) NOT NULL, `description` text NULL, `type` varchar(24) NOT NULL DEFAULT 'quiz', `passScore` int NOT NULL DEFAULT 60, `maxAttempts` int NOT NULL DEFAULT 1, `dueAt` datetime NULL, `allowLateSubmission` tinyint NOT NULL DEFAULT 0, `status` varchar(24) NOT NULL DEFAULT 'draft', `sortOrder` int NOT NULL DEFAULT 0, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX `IDX_course_assessments_course_status` (`courseId`,`status`), PRIMARY KEY (`id`), CONSTRAINT `FK_course_assessment_course` FOREIGN KEY (`courseId`) REFERENCES `courses`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_course_assessment_tenant` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE SET NULL) ENGINE=InnoDB");
    await q.query("CREATE TABLE `course_questions` (`id` int NOT NULL AUTO_INCREMENT, `assessmentId` int NOT NULL, `type` varchar(24) NOT NULL, `stem` text NOT NULL, `options` json NULL, `correctAnswer` json NULL, `explanation` text NULL, `score` decimal(8,2) NOT NULL DEFAULT 10, `sortOrder` int NOT NULL DEFAULT 0, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX `IDX_course_questions_assessment_sort` (`assessmentId`,`sortOrder`), PRIMARY KEY (`id`), CONSTRAINT `FK_course_question_assessment` FOREIGN KEY (`assessmentId`) REFERENCES `course_assessments`(`id`) ON DELETE CASCADE) ENGINE=InnoDB");
    await q.query("CREATE TABLE `course_assessment_attempts` (`id` int NOT NULL AUTO_INCREMENT, `userId` int NOT NULL, `courseId` int NOT NULL, `assessmentId` int NOT NULL, `attemptNo` int NOT NULL, `status` varchar(24) NOT NULL DEFAULT 'in_progress', `objectiveScore` decimal(8,2) NOT NULL DEFAULT 0, `manualScore` decimal(8,2) NOT NULL DEFAULT 0, `totalScore` decimal(8,2) NOT NULL DEFAULT 0, `submittedAt` datetime NULL, `reviewedAt` datetime NULL, `reviewedByAdminId` int NULL, `reviewRemark` text NULL, `lateSubmission` tinyint NOT NULL DEFAULT 0, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_course_attempt_user_assessment_no` (`userId`,`assessmentId`,`attemptNo`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
    await q.query("CREATE TABLE `course_assessment_answers` (`id` int NOT NULL AUTO_INCREMENT, `attemptId` int NOT NULL, `questionId` int NOT NULL, `answer` json NULL, `essayAnswer` text NULL, `correct` tinyint NULL, `score` decimal(8,2) NOT NULL DEFAULT 0, `feedback` text NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_course_answer_attempt_question` (`attemptId`,`questionId`), PRIMARY KEY (`id`), CONSTRAINT `FK_course_answer_attempt` FOREIGN KEY (`attemptId`) REFERENCES `course_assessment_attempts`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_course_answer_question` FOREIGN KEY (`questionId`) REFERENCES `course_questions`(`id`) ON DELETE CASCADE) ENGINE=InnoDB");
    await q.query("CREATE TABLE `course_assessment_grants` (`id` int NOT NULL AUTO_INCREMENT, `assessmentId` int NOT NULL, `userId` int NOT NULL, `additionalAttempts` int NOT NULL DEFAULT 0, `lateUntil` datetime NULL, `reason` varchar(500) NULL, `grantedByAdminId` int NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_course_assessment_grant_user` (`assessmentId`,`userId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
  }
  async down(q: QueryRunner): Promise<void> { await q.query("DROP TABLE `course_assessment_grants`"); await q.query("DROP TABLE `course_assessment_answers`"); await q.query("DROP TABLE `course_assessment_attempts`"); await q.query("DROP TABLE `course_questions`"); await q.query("DROP TABLE `course_assessments`"); }
}
