import { MigrationInterface, QueryRunner } from "typeorm";
export class CourseEngagementCertificates1783480000000 implements MigrationInterface {
  name = "CourseEngagementCertificates1783480000000";
  async up(q: QueryRunner): Promise<void> {
    await q.query("CREATE TABLE `course_reviews` (`id` int NOT NULL AUTO_INCREMENT, `userId` int NOT NULL, `courseId` int NOT NULL, `tenantId` int NULL, `rating` int NOT NULL, `content` text NOT NULL, `images` json NULL, `status` varchar(24) NOT NULL DEFAULT 'pending', `reply` text NULL, `repliedAt` datetime NULL, `repliedByAdminId` int NULL, `moderationReason` varchar(500) NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_course_review_user_course` (`userId`,`courseId`), INDEX `IDX_course_review_course_status` (`courseId`,`status`), PRIMARY KEY (`id`), CONSTRAINT `FK_course_review_course` FOREIGN KEY (`courseId`) REFERENCES `courses`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_course_review_tenant` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE SET NULL) ENGINE=InnoDB");
    await q.query("CREATE TABLE `course_qa` (`id` int NOT NULL AUTO_INCREMENT, `userId` int NOT NULL, `courseId` int NOT NULL, `lessonId` int NULL, `tenantId` int NULL, `title` varchar(200) NOT NULL, `content` text NOT NULL, `status` varchar(24) NOT NULL DEFAULT 'open', `answer` text NULL, `answeredAt` datetime NULL, `answeredByAdminId` int NULL, `featured` tinyint NOT NULL DEFAULT 0, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX `IDX_course_qa_course_status` (`courseId`,`status`), PRIMARY KEY (`id`), CONSTRAINT `FK_course_qa_course` FOREIGN KEY (`courseId`) REFERENCES `courses`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_course_qa_tenant` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE SET NULL) ENGINE=InnoDB");
    await q.query("CREATE TABLE `course_announcements` (`id` int NOT NULL AUTO_INCREMENT, `courseId` int NOT NULL, `tenantId` int NULL, `title` varchar(200) NOT NULL, `content` text NOT NULL, `status` varchar(24) NOT NULL DEFAULT 'draft', `publishAt` datetime NULL, `expiresAt` datetime NULL, `notifyLearners` tinyint NOT NULL DEFAULT 0, `notifiedAt` datetime NULL, `createdByAdminId` int NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX `IDX_course_announcement_course_publish` (`courseId`,`status`,`publishAt`), PRIMARY KEY (`id`), CONSTRAINT `FK_course_announcement_course` FOREIGN KEY (`courseId`) REFERENCES `courses`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_course_announcement_tenant` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE SET NULL) ENGINE=InnoDB");
    await q.query("CREATE TABLE `course_certificate_templates` (`id` int NOT NULL AUTO_INCREMENT, `courseId` int NOT NULL, `tenantId` int NULL, `name` varchar(160) NOT NULL, `backgroundUrl` varchar(500) NULL, `issuerName` varchar(160) NULL, `description` text NULL, `completionThreshold` int NOT NULL DEFAULT 100, `requireAssessmentPass` tinyint NOT NULL DEFAULT 0, `enabled` tinyint NOT NULL DEFAULT 1, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_course_certificate_template_course` (`courseId`), PRIMARY KEY (`id`), CONSTRAINT `FK_course_certificate_template_course` FOREIGN KEY (`courseId`) REFERENCES `courses`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_course_certificate_template_tenant` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE SET NULL) ENGINE=InnoDB");
    await q.query("ALTER TABLE `certificates` ADD `tenantId` int NULL, ADD `courseId` int NULL, ADD `courseTemplateId` int NULL, ADD `businessSnapshot` json NULL");
    await q.query("CREATE INDEX `IDX_certificates_course_user` ON `certificates` (`courseId`,`userId`)");
    await q.query("ALTER TABLE `course_orders` MODIFY `status` enum('pending_payment','paid','partially_refunded','refunded','closed') NOT NULL");
    await q.query("CREATE TABLE `course_refunds` (`id` int NOT NULL AUTO_INCREMENT, `refundNo` varchar(64) NOT NULL, `orderId` int NOT NULL, `amountFen` bigint NOT NULL, `reason` varchar(500) NOT NULL, `status` varchar(24) NOT NULL DEFAULT 'pending', `reviewRemark` varchar(500) NULL, `reviewedByAdminId` int NULL, `reviewedAt` datetime NULL, `completedAt` datetime NULL, `providerRefundNo` varchar(128) NULL, `failureReason` varchar(500) NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_course_refund_no` (`refundNo`), PRIMARY KEY (`id`), CONSTRAINT `FK_course_refund_order` FOREIGN KEY (`orderId`) REFERENCES `course_orders`(`id`) ON DELETE CASCADE) ENGINE=InnoDB");
  }
  async down(q: QueryRunner): Promise<void> { await q.query("DROP TABLE `course_refunds`"); await q.query("ALTER TABLE `course_orders` MODIFY `status` enum('pending_payment','paid','closed') NOT NULL"); await q.query("DROP INDEX `IDX_certificates_course_user` ON `certificates`"); await q.query("ALTER TABLE `certificates` DROP COLUMN `businessSnapshot`, DROP COLUMN `courseTemplateId`, DROP COLUMN `courseId`, DROP COLUMN `tenantId`"); await q.query("DROP TABLE `course_certificate_templates`"); await q.query("DROP TABLE `course_announcements`"); await q.query("DROP TABLE `course_qa`"); await q.query("DROP TABLE `course_reviews`"); }
}
