import { MigrationInterface, QueryRunner } from "typeorm";

export class MemberSegments1783370000000 implements MigrationInterface {
  name = "MemberSegments1783370000000";
  async up(queryRunner: QueryRunner) {
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS member_segments (id INT NOT NULL AUTO_INCREMENT, tenantId INT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) NULL, rules JSON NOT NULL, enabled TINYINT NOT NULL DEFAULT 1, lastMatchedCount INT NOT NULL DEFAULT 0, lastCalculatedAt DATETIME NULL, createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY UQ_member_segment_tenant_name (tenantId, name), KEY IDX_member_segment_tenant_enabled (tenantId, enabled), CONSTRAINT FK_member_segment_tenant FOREIGN KEY (tenantId) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS member_segment_snapshots (id INT NOT NULL AUTO_INCREMENT, snapshotNo VARCHAR(64) NOT NULL, tenantId INT NULL, segmentId INT NOT NULL, name VARCHAR(120) NOT NULL, rulesSnapshot JSON NOT NULL, memberCount INT NOT NULL DEFAULT 0, createdBy VARCHAR(100) NULL, createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY UQ_member_segment_snapshot_no (snapshotNo), KEY IDX_member_segment_snapshot_segment_created (segmentId, createdAt), CONSTRAINT FK_member_segment_snapshot_tenant FOREIGN KEY (tenantId) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT FK_member_segment_snapshot_segment FOREIGN KEY (segmentId) REFERENCES member_segments(id) ON DELETE CASCADE) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS member_segment_snapshot_members (id INT NOT NULL AUTO_INCREMENT, snapshotId INT NOT NULL, userId INT NOT NULL, createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY UQ_segment_snapshot_user (snapshotId, userId), KEY IDX_segment_snapshot_member_user (userId), CONSTRAINT FK_segment_snapshot_member_snapshot FOREIGN KEY (snapshotId) REFERENCES member_segment_snapshots(id) ON DELETE CASCADE, CONSTRAINT FK_segment_snapshot_member_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB`);
  }
  async down(queryRunner: QueryRunner) { await queryRunner.query("DROP TABLE IF EXISTS member_segment_snapshot_members"); await queryRunner.query("DROP TABLE IF EXISTS member_segment_snapshots"); await queryRunner.query("DROP TABLE IF EXISTS member_segments"); }
}
