<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { ElMessage } from "element-plus";
import { api } from "../api";

const activities = ref<any[]>([]); const selectedId = ref<number>(); const announcements = ref<any[]>([]); const posts = ref<any[]>([]); const loading = ref(false); const saving = ref(false);
const form = ref({ title: "", content: "", status: "published", pinned: false, publishAt: "" });
async function loadOptions(){ const result:any=await api.get("/admin/reviews/options"); activities.value=result?.activities||[]; if(!selectedId.value) selectedId.value=activities.value[0]?.id; }
async function load(){ if(!selectedId.value)return; loading.value=true; try{ const [notice, post]:any=await Promise.all([api.get(`/admin/activities/${selectedId.value}/space/announcements`),api.get("/admin/activity-space-posts",{params:{activityId:selectedId.value,pageSize:50}})]); announcements.value=notice||[];posts.value=post?.items||[];}finally{loading.value=false;} }
async function publish(){if(!selectedId.value||!form.value.title.trim()||!form.value.content.trim())return ElMessage.error("请填写公告标题和内容");saving.value=true;try{await api.post(`/admin/activities/${selectedId.value}/space/announcements`,{...form.value,publishAt:form.value.publishAt||null});form.value={title:"",content:"",status:"published",pinned:false,publishAt:""};ElMessage.success("活动公告已保存");await load();}finally{saving.value=false;}}
async function moderate(row:any,status:string){await api.patch(`/admin/activity-space-posts/${row.id}`,{status,adminReply:row.adminReply||""});ElMessage.success(status==="hidden"?"已隐藏":"已通过并回复");await load();}
watch(selectedId,()=>void load());onMounted(async()=>{await loadOptions();await load();});
</script>
<template><section class="activity-space-admin"><el-card><template #header>活动空间运营</template><el-select v-model="selectedId" filterable placeholder="选择活动" style="width:360px"><el-option v-for="item in activities" :key="item.id" :label="item.title" :value="item.id"/></el-select></el-card><el-row :gutter="16"><el-col :md="10"><el-card><template #header>发布活动公告</template><el-form label-position="top"><el-form-item label="标题"><el-input v-model="form.title" maxlength="160" show-word-limit/></el-form-item><el-form-item label="内容"><el-input v-model="form.content" type="textarea" :rows="7" maxlength="20000" show-word-limit/></el-form-item><el-form-item><el-checkbox v-model="form.pinned">置顶</el-checkbox></el-form-item><el-button type="success" :loading="saving" @click="publish">发布公告</el-button></el-form></el-card></el-col><el-col :md="14"><el-card><template #header>已发布公告</template><el-empty v-if="!announcements.length && !loading" description="暂无活动公告"/><el-timeline v-else><el-timeline-item v-for="item in announcements" :key="item.id" :timestamp="item.publishAt || item.createdAt"><strong>{{ item.title }}</strong><p>{{ item.content }}</p><el-tag size="small">{{ item.status }}</el-tag></el-timeline-item></el-timeline></el-card></el-col></el-row><el-card><template #header>活动问答审核</template><el-table :data="posts" v-loading="loading"><el-table-column prop="activity.title" label="活动" min-width="160"/><el-table-column prop="user.nickname" label="参与者" width="110"/><el-table-column prop="content" label="内容" min-width="260"/><el-table-column prop="reportCount" label="举报" width="80"/><el-table-column label="主办方回复" min-width="220"><template #default="{row}"><el-input v-model="row.adminReply" type="textarea" :rows="2" maxlength="500" placeholder="可填写回复后通过"/></template></el-table-column><el-table-column prop="status" label="状态" width="90"/><el-table-column label="操作" width="170"><template #default="{row}"><el-button link type="success" @click="moderate(row,'visible')">{{ row.status === 'pending' ? '通过' : '保存回复' }}</el-button><el-button link type="danger" @click="moderate(row,'hidden')">隐藏</el-button></template></el-table-column></el-table></el-card></section></template>
<style scoped>.activity-space-admin{display:grid;gap:16px}.el-row{margin:0!important}.el-card{margin-bottom:0}p{white-space:pre-wrap;color:#526057;line-height:1.55}</style>
