<template>
  <view class="search-page">
    <view class="search-bar"><view class="input-wrap"><view class="search-glyph" aria-hidden="true" /><input v-model="keyword" placeholder="搜索活动、地点或主办方" confirm-type="search" @confirm="load" /></view><text @click="goBack">取消</text></view>
    <view class="filter-row"><text :class="{ active: filter === 'all' }" @click="selectFilter('all')">全部</text><text :class="{ active: filter === 'open' }" @click="selectFilter('open')">报名中</text><text :class="{ active: filter === 'free' }" @click="selectFilter('free')">免费</text></view>
    <view v-if="loading" class="state">正在搜索活动...</view><view v-else-if="error" class="state error">{{ error }}<text @click="load">重新加载</text></view>
    <template v-else><view v-if="!keyword" class="search-intro"><text>发现适合你的线下活动</text><text>输入活动名称、地点或关键词开始搜索</text></view><text v-else class="result-title">找到 {{ results.length }} 场活动</text><view v-for="(item, index) in results" :key="item.id" class="activity-card app-stagger app-press" :style="motionStyle(index * 42)" role="button" tabindex="0" :aria-label="`查看活动：${item.title}`" @click="openDetail(item)" @keyup.enter="openDetail(item)" @keyup.space.prevent="openDetail(item)"><image v-if="item.coverUrl" :src="item.coverUrl" mode="aspectFill" /><view v-else class="cover-empty">{{ item.category?.name || "活动" }}</view><view class="card-copy"><view><text class="date">{{ dateText(item.startTime) }}</text><text class="status">{{ statusText(item.displayStatus || item.status) }}</text></view><text class="title">{{ item.title }}</text><text class="meta">{{ timeText(item.startTime) }} · {{ item.location || "地点待确认" }}</text><view class="foot"><text>{{ item.registeredCount || 0 }} 人已报名</text><text>{{ priceText(item.price) }}</text></view></view></view><view v-if="keyword && !results.length" class="state">没有匹配活动，换个关键词试试。</view></template>
  </view>
</template>
<script setup lang="ts">
import { computed, ref } from "vue";
import { onShow } from "@dcloudio/uni-app";
import { request, withTenantCode } from "../../api";
import { createTenantLoadGuard } from "../../tenant-load-guard";
import { reviewSafeText } from "../../review-safe-text";
import { motionStyle } from "../../motion/platform-adapter";
const keyword = ref(""); const filter = ref("all"); const rows = ref<any[]>([]); const loading = ref(false); const error = ref("");
const loadGuard = createTenantLoadGuard();
const results = computed(() => filter.value === "free" ? rows.value.filter((item) => Number(item.price || 0) <= 0) : rows.value);
async function load(){ const token = loadGuard.begin(); loading.value=true; error.value=""; rows.value=[]; try { const params = [`page=1`,`pageSize=50`]; if(keyword.value.trim()) params.push(`keyword=${encodeURIComponent(keyword.value.trim())}`); if(filter.value === "open") params.push("status=open"); const result:any = await request(`/public/activities?${params.join("&")}`); if (!loadGuard.isCurrent(token)) return; rows.value = Array.isArray(result) ? result : result?.items || []; } catch(e:any){ if (loadGuard.isCurrent(token)) error.value=reviewSafeText(e?.message||"活动搜索失败"); } finally { if (loadGuard.isCurrent(token)) loading.value=false; } }
function selectFilter(next:string){ filter.value=next; void load(); } function goBack(){ uni.navigateBack(); } function openDetail(item:any){ uni.navigateTo({url:withTenantCode(`/pages/activity/detail?id=${item.id}`)}); } function dateText(value:string){ const d=new Date(value); return Number.isNaN(d.getTime())?"日期待定":`${d.getMonth()+1}月${d.getDate()}日`; } function timeText(value:string){ const d=new Date(value); return Number.isNaN(d.getTime())?"时间待定":`${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`; } function priceText(value:any){return Number(value||0)>0?`￥${Number(value).toFixed(2)}`:"免费";} function statusText(value:string){return value==="full"?"已满员":value==="ended"?"已结束":"报名中";}
onShow(()=>void load());
</script>
<style scoped>
.search-page{min-height:100vh;padding:20rpx 24rpx 48rpx;box-sizing:border-box;background:#f6f8f7;font-family:-apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif}.search-bar{display:flex;align-items:center;gap:20rpx;color:#3a4a42;font-size:25rpx}.input-wrap{height:74rpx;flex:1;display:flex;align-items:center;gap:14rpx;padding:0 22rpx;border-radius:8rpx;background:#fff;border:1rpx solid #e2eae6}.input-wrap text{color:#078347;font-weight:900}.input-wrap input{flex:1;font-size:25rpx;color:#173024}.filter-row{display:flex;gap:14rpx;margin:22rpx 0}.filter-row text{padding:11rpx 20rpx;border-radius:8rpx;background:#fff;color:#66766e;font-size:23rpx}.filter-row .active{background:#20d477;color:#072d19;font-weight:900}.search-intro{display:grid;gap:12rpx;margin-top:32rpx;padding:34rpx 28rpx;border-radius:8rpx;background:#eafbf1;color:#173c27}.search-intro text:first-child{font-size:34rpx;font-weight:950}.search-intro text:last-child{font-size:23rpx;color:#648171}.result-title{display:block;margin:12rpx 0 16rpx;color:#5c6b63;font-size:23rpx}.activity-card{display:flex;gap:16rpx;margin-bottom:16rpx;padding:14rpx;border:1rpx solid #e2eae6;border-radius:8rpx;background:#fff}.activity-card image,.cover-empty{width:190rpx;height:150rpx;flex:0 0 auto;border-radius:6rpx;background:#eafbf1}.cover-empty{display:grid;place-items:center;color:#08753f;font-size:23rpx;font-weight:900}.card-copy{min-width:0;flex:1;display:grid;align-content:center;gap:8rpx}.card-copy>view:first-child{display:flex;gap:8rpx}.date,.status{padding:3rpx 7rpx;border-radius:4rpx;background:#eef2f0;color:#5c6b63;font-size:18rpx}.status{background:#eafbf1;color:#08753f}.title{display:-webkit-box;overflow:hidden;color:#14281c;font-size:27rpx;font-weight:900;line-height:1.35;-webkit-line-clamp:2;-webkit-box-orient:vertical}.meta{overflow:hidden;color:#75847c;font-size:20rpx;text-overflow:ellipsis;white-space:nowrap}.foot{display:flex;justify-content:space-between;gap:8rpx;color:#86938c;font-size:19rpx}.foot text:last-child{color:#dc6900;font-size:23rpx;font-weight:900}.state{margin-top:22rpx;padding:28rpx;border-radius:8rpx;background:#fff;color:#6b7b72;font-size:24rpx;text-align:center}.state.error{color:#b91c1c}.state.error text{display:block;margin-top:12rpx;color:#08753f;font-weight:900}
.search-page{padding:24rpx 28rpx 48rpx;background:var(--app-page-bg)}
.input-wrap{height:80rpx;border-color:var(--app-border);border-radius:14rpx}
.search-glyph{position:relative;width:24rpx;height:24rpx;border:3rpx solid #52636b;border-radius:50%}.search-glyph::after{position:absolute;right:-7rpx;bottom:-5rpx;width:9rpx;height:3rpx;border-radius:3rpx;background:#52636b;content:"";transform:rotate(45deg)}
.filter-row text{border:1rpx solid var(--app-border);border-radius:12rpx}.filter-row .active{border-color:#0f766e;background:#0f766e;color:#fff}
.search-intro,.state,.activity-card{border:1rpx solid var(--app-border);border-radius:16rpx;box-shadow:none}
.search-intro{background:#eaf7f1;color:var(--app-text)}
.activity-card image,.cover-empty{border-radius:12rpx}.title{color:var(--app-text)}.foot text:last-child{color:var(--app-price)}
</style>
